encoder_op_list_name_dict = {
    "1x1_ry": [
        {"input_idx": [0], "func": "ry", "wires": [0]},
    ],
    "2x1_ryry": [
        {"input_idx": [0], "func": "ry", "wires": [0]},
        {"input_idx": [1], "func": "ry", "wires": [1]},
    ],
    "2x8_rxryrzrxryrzrxry": [
        {"input_idx": [0], "func": "rx", "wires": [0]},
        {"input_idx": [1], "func": "rx", "wires": [1]},
        {"input_idx": [2], "func": "ry", "wires": [0]},
        {"input_idx": [3], "func": "ry", "wires": [1]},
        {"input_idx": [4], "func": "rz", "wires": [0]},
        {"input_idx": [5], "func": "rz", "wires": [1]},
        {"input_idx": [6], "func": "rx", "wires": [0]},
        {"input_idx": [7], "func": "rx", "wires": [1]},
        {"input_idx": [8], "func": "ry", "wires": [0]},
        {"input_idx": [9], "func": "ry", "wires": [1]},
        {"input_idx": [10], "func": "rz", "wires": [0]},
        {"input_idx": [11], "func": "rz", "wires": [1]},
        {"input_idx": [12], "func": "rx", "wires": [0]},
        {"input_idx": [13], "func": "rx", "wires": [1]},
        {"input_idx": [14], "func": "ry", "wires": [0]},
        {"input_idx": [15], "func": "ry", "wires": [1]},
    ],
    "3x1_ryryry": [
        {"input_idx": [0], "func": "ry", "wires": [0]},
        {"input_idx": [1], "func": "ry", "wires": [1]},
        {"input_idx": [2], "func": "ry", "wires": [2]},
    ],
    "3x1_rxrxrx": [
        {"input_idx": [0], "func": "rx", "wires": [0]},
        {"input_idx": [1], "func": "rx", "wires": [1]},
        {"input_idx": [2], "func": "rx", "wires": [2]},
    ],
    "4_ry": [
        {"input_idx": [0], "func": "ry", "wires": [0]},
        {"input_idx": [1], "func": "ry", "wires": [1]},
        {"input_idx": [2], "func": "ry", "wires": [2]},
        {"input_idx": [3], "func": "ry", "wires": [3]},
    ],
    "4x4_u3rx": [
        {"input_idx": [0, 1, 2], "func": "u3", "wires": [0]},
        {"input_idx": [3], "func": "rx", "wires": [0]},
        {"input_idx": [4, 5, 6], "func": "u3", "wires": [1]},
        {"input_idx": [7], "func": "rx", "wires": [1]},
        {"input_idx": [8, 9, 10], "func": "u3", "wires": [2]},
        {"input_idx": [11], "func": "rx", "wires": [2]},
        {"input_idx": [12, 13, 14], "func": "u3", "wires": [3]},
        {"input_idx": [15], "func": "rx", "wires": [3]},
    ],
    "4x4_ryzxy": [
        {"input_idx": [0], "func": "ry", "wires": [0]},
        {"input_idx": [1], "func": "ry", "wires": [1]},
        {"input_idx": [2], "func": "ry", "wires": [2]},
        {"input_idx": [3], "func": "ry", "wires": [3]},
        {"input_idx": [4], "func": "rz", "wires": [0]},
        {"input_idx": [5], "func": "rz", "wires": [1]},
        {"input_idx": [6], "func": "rz", "wires": [2]},
        {"input_idx": [7], "func": "rz", "wires": [3]},
        {"input_idx": [8], "func": "rx", "wires": [0]},
        {"input_idx": [9], "func": "rx", "wires": [1]},
        {"input_idx": [10], "func": "rx", "wires": [2]},
        {"input_idx": [11], "func": "rx", "wires": [3]},
        {"input_idx": [12], "func": "ry", "wires": [0]},
        {"input_idx": [13], "func": "ry", "wires": [1]},
        {"input_idx": [14], "func": "ry", "wires": [2]},
        {"input_idx": [15], "func": "ry", "wires": [3]},
    ],
    "8x2_ry": [
        {"input_idx": [0], "func": "ry", "wires": [0]},
        {"input_idx": [1], "func": "ry", "wires": [1]},
        {"input_idx": [2], "func": "ry", "wires": [2]},
        {"input_idx": [3], "func": "ry", "wires": [3]},
        {"input_idx": [4], "func": "ry", "wires": [4]},
        {"input_idx": [5], "func": "ry", "wires": [5]},
        {"input_idx": [6], "func": "ry", "wires": [6]},
        {"input_idx": [7], "func": "ry", "wires": [7]},
        {"input_idx": [8], "func": "ry", "wires": [0]},
        {"input_idx": [9], "func": "ry", "wires": [1]},
        {"input_idx": [10], "func": "ry", "wires": [2]},
        {"input_idx": [11], "func": "ry", "wires": [3]},
        {"input_idx": [12], "func": "ry", "wires": [4]},
        {"input_idx": [13], "func": "ry", "wires": [5]},
        {"input_idx": [14], "func": "ry", "wires": [6]},
        {"input_idx": [15], "func": "ry", "wires": [7]},
    ],
    "16_ry": [
        {"input_idx": [0], "func": "ry", "wires": [0]},
        {"input_idx": [1], "func": "ry", "wires": [1]},
        {"input_idx": [2], "func": "ry", "wires": [2]},
        {"input_idx": [3], "func": "ry", "wires": [3]},
        {"input_idx": [4], "func": "ry", "wires": [4]},
        {"input_idx": [5], "func": "ry", "wires": [5]},
        {"input_idx": [6], "func": "ry", "wires": [6]},
        {"input_idx": [7], "func": "ry", "wires": [7]},
        {"input_idx": [8], "func": "ry", "wires": [8]},
        {"input_idx": [9], "func": "ry", "wires": [9]},
        {"input_idx": [10], "func": "ry", "wires": [10]},
        {"input_idx": [11], "func": "ry", "wires": [11]},
        {"input_idx": [12], "func": "ry", "wires": [12]},
        {"input_idx": [13], "func": "ry", "wires": [13]},
        {"input_idx": [14], "func": "ry", "wires": [14]},
        {"input_idx": [15], "func": "ry", "wires": [15]},
    ],
    "4x4_rzsx": [
        {"input_idx": [0], "func": "rz", "wires": [0]},
        {"input_idx": None, "func": "sx", "wires": [0]},
        {"input_idx": [1], "func": "rz", "wires": [1]},
        {"input_idx": None, "func": "sx", "wires": [1]},
        {"input_idx": [2], "func": "rz", "wires": [2]},
        {"input_idx": None, "func": "sx", "wires": [2]},
        {"input_idx": [3], "func": "rz", "wires": [3]},
        {"input_idx": None, "func": "sx", "wires": [3]},
        {"input_idx": [4], "func": "rz", "wires": [0]},
        {"input_idx": None, "func": "sx", "wires": [0]},
        {"input_idx": [5], "func": "rz", "wires": [1]},
        {"input_idx": None, "func": "sx", "wires": [1]},
        {"input_idx": [6], "func": "rz", "wires": [2]},
        {"input_idx": None, "func": "sx", "wires": [2]},
        {"input_idx": [7], "func": "rz", "wires": [3]},
        {"input_idx": None, "func": "sx", "wires": [3]},
        {"input_idx": [8], "func": "rz", "wires": [0]},
        {"input_idx": None, "func": "sx", "wires": [0]},
        {"input_idx": [9], "func": "rz", "wires": [1]},
        {"input_idx": None, "func": "sx", "wires": [1]},
        {"input_idx": [10], "func": "rz", "wires": [2]},
        {"input_idx": None, "func": "sx", "wires": [2]},
        {"input_idx": [11], "func": "rz", "wires": [3]},
        {"input_idx": None, "func": "sx", "wires": [3]},
        {"input_idx": [12], "func": "rz", "wires": [0]},
        {"input_idx": None, "func": "sx", "wires": [0]},
        {"input_idx": [13], "func": "rz", "wires": [1]},
        {"input_idx": None, "func": "sx", "wires": [1]},
        {"input_idx": [14], "func": "rz", "wires": [2]},
        {"input_idx": None, "func": "sx", "wires": [2]},
        {"input_idx": [15], "func": "rz", "wires": [3]},
        {"input_idx": None, "func": "sx", "wires": [3]},
    ],
    "15_ryrz": [
        {"input_idx": [0], "func": "ry", "wires": [0]},
        {"input_idx": [1], "func": "ry", "wires": [1]},
        {"input_idx": [2], "func": "ry", "wires": [2]},
        {"input_idx": [3], "func": "ry", "wires": [3]},
        {"input_idx": [4], "func": "ry", "wires": [4]},
        {"input_idx": [5], "func": "ry", "wires": [5]},
        {"input_idx": [6], "func": "ry", "wires": [6]},
        {"input_idx": [7], "func": "ry", "wires": [7]},
        {"input_idx": [8], "func": "ry", "wires": [8]},
        {"input_idx": [9], "func": "ry", "wires": [9]},
        {"input_idx": [10], "func": "ry", "wires": [10]},
        {"input_idx": [11], "func": "ry", "wires": [11]},
        {"input_idx": [12], "func": "ry", "wires": [12]},
        {"input_idx": [13], "func": "ry", "wires": [13]},
        {"input_idx": [14], "func": "ry", "wires": [14]},
        {"input_idx": [15], "func": "rz", "wires": [0]},
    ],
    "2x8_ryzxyzxyz": [
        {"input_idx": [0], "func": "ry", "wires": [0]},
        {"input_idx": [1], "func": "ry", "wires": [1]},
        {"input_idx": [2], "func": "rz", "wires": [0]},
        {"input_idx": [3], "func": "rz", "wires": [1]},
        {"input_idx": [4], "func": "rx", "wires": [0]},
        {"input_idx": [5], "func": "rx", "wires": [1]},
        {"input_idx": [6], "func": "ry", "wires": [0]},
        {"input_idx": [7], "func": "ry", "wires": [1]},
        {"input_idx": [8], "func": "rz", "wires": [0]},
        {"input_idx": [9], "func": "rz", "wires": [1]},
        {"input_idx": [10], "func": "rx", "wires": [0]},
        {"input_idx": [11], "func": "rx", "wires": [1]},
        {"input_idx": [12], "func": "ry", "wires": [0]},
        {"input_idx": [13], "func": "ry", "wires": [1]},
        {"input_idx": [14], "func": "rz", "wires": [0]},
        {"input_idx": [15], "func": "rz", "wires": [1]},
    ],
    "10_ryzx": [
        {"input_idx": [0], "func": "ry", "wires": [0]},
        {"input_idx": [1], "func": "ry", "wires": [1]},
        {"input_idx": [2], "func": "ry", "wires": [2]},
        {"input_idx": [3], "func": "ry", "wires": [3]},
        {"input_idx": [4], "func": "rz", "wires": [0]},
        {"input_idx": [5], "func": "rz", "wires": [1]},
        {"input_idx": [6], "func": "rz", "wires": [2]},
        {"input_idx": [7], "func": "rz", "wires": [3]},
        {"input_idx": [8], "func": "rx", "wires": [0]},
        {"input_idx": [9], "func": "rx", "wires": [1]},
    ],
    "10_ry": [
        {"input_idx": [0], "func": "ry", "wires": [0]},
        {"input_idx": [1], "func": "ry", "wires": [1]},
        {"input_idx": [2], "func": "ry", "wires": [2]},
        {"input_idx": [3], "func": "ry", "wires": [3]},
        {"input_idx": [4], "func": "ry", "wires": [4]},
        {"input_idx": [5], "func": "ry", "wires": [5]},
        {"input_idx": [6], "func": "ry", "wires": [6]},
        {"input_idx": [7], "func": "ry", "wires": [7]},
        {"input_idx": [8], "func": "ry", "wires": [8]},
        {"input_idx": [9], "func": "ry", "wires": [9]},
    ],
    "25_ry": [
        {"input_idx": [0], "func": "ry", "wires": [0]},
        {"input_idx": [1], "func": "ry", "wires": [1]},
        {"input_idx": [2], "func": "ry", "wires": [2]},
        {"input_idx": [3], "func": "ry", "wires": [3]},
        {"input_idx": [4], "func": "ry", "wires": [4]},
        {"input_idx": [5], "func": "ry", "wires": [5]},
        {"input_idx": [6], "func": "ry", "wires": [6]},
        {"input_idx": [7], "func": "ry", "wires": [7]},
        {"input_idx": [8], "func": "ry", "wires": [8]},
        {"input_idx": [9], "func": "ry", "wires": [9]},
        {"input_idx": [10], "func": "ry", "wires": [10]},
        {"input_idx": [11], "func": "ry", "wires": [11]},
        {"input_idx": [12], "func": "ry", "wires": [12]},
        {"input_idx": [13], "func": "ry", "wires": [13]},
        {"input_idx": [14], "func": "ry", "wires": [14]},
        {"input_idx": [15], "func": "ry", "wires": [15]},
        {"input_idx": [16], "func": "ry", "wires": [16]},
        {"input_idx": [17], "func": "ry", "wires": [17]},
        {"input_idx": [18], "func": "ry", "wires": [18]},
        {"input_idx": [19], "func": "ry", "wires": [19]},
        {"input_idx": [20], "func": "ry", "wires": [20]},
        {"input_idx": [21], "func": "ry", "wires": [21]},
        {"input_idx": [22], "func": "ry", "wires": [22]},
        {"input_idx": [23], "func": "ry", "wires": [23]},
        {"input_idx": [24], "func": "ry", "wires": [24]},
    ],
    "25_ryrz": [
        {"input_idx": [0], "func": "ry", "wires": [0]},
        {"input_idx": [1], "func": "ry", "wires": [1]},
        {"input_idx": [2], "func": "ry", "wires": [2]},
        {"input_idx": [3], "func": "ry", "wires": [3]},
        {"input_idx": [4], "func": "ry", "wires": [4]},
        {"input_idx": [5], "func": "ry", "wires": [5]},
        {"input_idx": [6], "func": "ry", "wires": [6]},
        {"input_idx": [7], "func": "ry", "wires": [7]},
        {"input_idx": [8], "func": "ry", "wires": [8]},
        {"input_idx": [9], "func": "ry", "wires": [9]},
        {"input_idx": [10], "func": "ry", "wires": [10]},
        {"input_idx": [11], "func": "ry", "wires": [11]},
        {"input_idx": [12], "func": "ry", "wires": [12]},
        {"input_idx": [13], "func": "ry", "wires": [13]},
        {"input_idx": [14], "func": "ry", "wires": [14]},
        {"input_idx": [15], "func": "ry", "wires": [15]},
        {"input_idx": [16], "func": "ry", "wires": [16]},
        {"input_idx": [17], "func": "ry", "wires": [17]},
        {"input_idx": [18], "func": "ry", "wires": [18]},
        {"input_idx": [19], "func": "ry", "wires": [19]},
        {"input_idx": [20], "func": "ry", "wires": [20]},
        {"input_idx": [21], "func": "rz", "wires": [0]},
        {"input_idx": [22], "func": "rz", "wires": [1]},
        {"input_idx": [23], "func": "rz", "wires": [2]},
        {"input_idx": [24], "func": "rz", "wires": [3]},
    ],
    "6x6_ryzxy": [
        {"input_idx": [0], "func": "ry", "wires": [0]},
        {"input_idx": [1], "func": "ry", "wires": [1]},
        {"input_idx": [2], "func": "ry", "wires": [2]},
        {"input_idx": [3], "func": "ry", "wires": [3]},
        {"input_idx": [4], "func": "ry", "wires": [4]},
        {"input_idx": [5], "func": "ry", "wires": [5]},
        {"input_idx": [6], "func": "ry", "wires": [6]},
        {"input_idx": [7], "func": "ry", "wires": [7]},
        {"input_idx": [8], "func": "ry", "wires": [8]},
        {"input_idx": [9], "func": "ry", "wires": [9]},
        {"input_idx": [10], "func": "rz", "wires": [0]},
        {"input_idx": [11], "func": "rz", "wires": [1]},
        {"input_idx": [12], "func": "rz", "wires": [2]},
        {"input_idx": [13], "func": "rz", "wires": [3]},
        {"input_idx": [14], "func": "rz", "wires": [4]},
        {"input_idx": [15], "func": "rz", "wires": [5]},
        {"input_idx": [16], "func": "rz", "wires": [6]},
        {"input_idx": [17], "func": "rz", "wires": [7]},
        {"input_idx": [18], "func": "rz", "wires": [8]},
        {"input_idx": [19], "func": "rz", "wires": [9]},
        {"input_idx": [20], "func": "rx", "wires": [0]},
        {"input_idx": [21], "func": "rx", "wires": [1]},
        {"input_idx": [22], "func": "rx", "wires": [2]},
        {"input_idx": [23], "func": "rx", "wires": [3]},
        {"input_idx": [24], "func": "rx", "wires": [4]},
        {"input_idx": [25], "func": "rx", "wires": [5]},
        {"input_idx": [26], "func": "rx", "wires": [6]},
        {"input_idx": [27], "func": "rx", "wires": [7]},
        {"input_idx": [28], "func": "rx", "wires": [8]},
        {"input_idx": [29], "func": "rx", "wires": [9]},
        {"input_idx": [30], "func": "ry", "wires": [0]},
        {"input_idx": [31], "func": "ry", "wires": [1]},
        {"input_idx": [32], "func": "ry", "wires": [2]},
        {"input_idx": [33], "func": "ry", "wires": [3]},
        {"input_idx": [34], "func": "ry", "wires": [4]},
        {"input_idx": [35], "func": "ry", "wires": [5]},
    ],
    "6x6_ryrz": [
        {"input_idx": [0], "func": "ry", "wires": [0]},
        {"input_idx": [1], "func": "ry", "wires": [1]},
        {"input_idx": [2], "func": "ry", "wires": [2]},
        {"input_idx": [3], "func": "ry", "wires": [3]},
        {"input_idx": [4], "func": "ry", "wires": [4]},
        {"input_idx": [5], "func": "ry", "wires": [5]},
        {"input_idx": [6], "func": "ry", "wires": [6]},
        {"input_idx": [7], "func": "ry", "wires": [7]},
        {"input_idx": [8], "func": "ry", "wires": [8]},
        {"input_idx": [9], "func": "ry", "wires": [9]},
        {"input_idx": [10], "func": "ry", "wires": [10]},
        {"input_idx": [11], "func": "ry", "wires": [11]},
        {"input_idx": [12], "func": "ry", "wires": [12]},
        {"input_idx": [13], "func": "ry", "wires": [13]},
        {"input_idx": [14], "func": "ry", "wires": [14]},
        {"input_idx": [15], "func": "ry", "wires": [15]},
        {"input_idx": [16], "func": "ry", "wires": [16]},
        {"input_idx": [17], "func": "ry", "wires": [17]},
        {"input_idx": [18], "func": "ry", "wires": [18]},
        {"input_idx": [19], "func": "ry", "wires": [19]},
        {"input_idx": [20], "func": "ry", "wires": [20]},
        {"input_idx": [21], "func": "rz", "wires": [0]},
        {"input_idx": [22], "func": "rz", "wires": [1]},
        {"input_idx": [23], "func": "rz", "wires": [2]},
        {"input_idx": [24], "func": "rz", "wires": [3]},
        {"input_idx": [25], "func": "rz", "wires": [4]},
        {"input_idx": [26], "func": "rz", "wires": [5]},
        {"input_idx": [27], "func": "rz", "wires": [6]},
        {"input_idx": [28], "func": "rz", "wires": [7]},
        {"input_idx": [29], "func": "rz", "wires": [8]},
        {"input_idx": [30], "func": "rz", "wires": [9]},
        {"input_idx": [31], "func": "rz", "wires": [10]},
        {"input_idx": [32], "func": "rz", "wires": [11]},
        {"input_idx": [33], "func": "rz", "wires": [12]},
        {"input_idx": [34], "func": "rz", "wires": [13]},
        {"input_idx": [35], "func": "rz", "wires": [14]},
    ],
    "6x6_ryrzrx": [
        {"input_idx": [0], "func": "ry", "wires": [0]},
        {"input_idx": [1], "func": "ry", "wires": [1]},
        {"input_idx": [2], "func": "ry", "wires": [2]},
        {"input_idx": [3], "func": "ry", "wires": [3]},
        {"input_idx": [4], "func": "ry", "wires": [4]},
        {"input_idx": [5], "func": "ry", "wires": [5]},
        {"input_idx": [6], "func": "ry", "wires": [6]},
        {"input_idx": [7], "func": "ry", "wires": [7]},
        {"input_idx": [8], "func": "ry", "wires": [8]},
        {"input_idx": [9], "func": "ry", "wires": [9]},
        {"input_idx": [10], "func": "ry", "wires": [10]},
        {"input_idx": [11], "func": "ry", "wires": [11]},
        {"input_idx": [12], "func": "ry", "wires": [12]},
        {"input_idx": [13], "func": "ry", "wires": [13]},
        {"input_idx": [14], "func": "ry", "wires": [14]},
        {"input_idx": [15], "func": "ry", "wires": [15]},
        {"input_idx": [16], "func": "rz", "wires": [0]},
        {"input_idx": [17], "func": "rz", "wires": [1]},
        {"input_idx": [18], "func": "rz", "wires": [2]},
        {"input_idx": [19], "func": "rz", "wires": [3]},
        {"input_idx": [20], "func": "rz", "wires": [4]},
        {"input_idx": [21], "func": "rz", "wires": [5]},
        {"input_idx": [22], "func": "rz", "wires": [6]},
        {"input_idx": [23], "func": "rz", "wires": [7]},
        {"input_idx": [24], "func": "rz", "wires": [8]},
        {"input_idx": [25], "func": "rz", "wires": [9]},
        {"input_idx": [26], "func": "rz", "wires": [10]},
        {"input_idx": [27], "func": "rz", "wires": [11]},
        {"input_idx": [28], "func": "rz", "wires": [12]},
        {"input_idx": [29], "func": "rz", "wires": [13]},
        {"input_idx": [30], "func": "rz", "wires": [14]},
        {"input_idx": [31], "func": "rz", "wires": [15]},
        {"input_idx": [32], "func": "rx", "wires": [0]},
        {"input_idx": [33], "func": "rx", "wires": [1]},
        {"input_idx": [34], "func": "rx", "wires": [2]},
        {"input_idx": [35], "func": "rx", "wires": [3]},
    ],
    "10x10_ryzxyzxyzxy": [
        {"input_idx": [0], "func": "ry", "wires": [0]},
        {"input_idx": [1], "func": "ry", "wires": [1]},
        {"input_idx": [2], "func": "ry", "wires": [2]},
        {"input_idx": [3], "func": "ry", "wires": [3]},
        {"input_idx": [4], "func": "ry", "wires": [4]},
        {"input_idx": [5], "func": "ry", "wires": [5]},
        {"input_idx": [6], "func": "ry", "wires": [6]},
        {"input_idx": [7], "func": "ry", "wires": [7]},
        {"input_idx": [8], "func": "ry", "wires": [8]},
        {"input_idx": [9], "func": "ry", "wires": [9]},
        {"input_idx": [10], "func": "rz", "wires": [0]},
        {"input_idx": [11], "func": "rz", "wires": [1]},
        {"input_idx": [12], "func": "rz", "wires": [2]},
        {"input_idx": [13], "func": "rz", "wires": [3]},
        {"input_idx": [14], "func": "rz", "wires": [4]},
        {"input_idx": [15], "func": "rz", "wires": [5]},
        {"input_idx": [16], "func": "rz", "wires": [6]},
        {"input_idx": [17], "func": "rz", "wires": [7]},
        {"input_idx": [18], "func": "rz", "wires": [8]},
        {"input_idx": [19], "func": "rz", "wires": [9]},
        {"input_idx": [20], "func": "rx", "wires": [0]},
        {"input_idx": [21], "func": "rx", "wires": [1]},
        {"input_idx": [22], "func": "rx", "wires": [2]},
        {"input_idx": [23], "func": "rx", "wires": [3]},
        {"input_idx": [24], "func": "rx", "wires": [4]},
        {"input_idx": [25], "func": "rx", "wires": [5]},
        {"input_idx": [26], "func": "rx", "wires": [6]},
        {"input_idx": [27], "func": "rx", "wires": [7]},
        {"input_idx": [28], "func": "rx", "wires": [8]},
        {"input_idx": [29], "func": "rx", "wires": [9]},
        {"input_idx": [30], "func": "ry", "wires": [0]},
        {"input_idx": [31], "func": "ry", "wires": [1]},
        {"input_idx": [32], "func": "ry", "wires": [2]},
        {"input_idx": [33], "func": "ry", "wires": [3]},
        {"input_idx": [34], "func": "ry", "wires": [4]},
        {"input_idx": [35], "func": "ry", "wires": [5]},
        {"input_idx": [36], "func": "ry", "wires": [6]},
        {"input_idx": [37], "func": "ry", "wires": [7]},
        {"input_idx": [38], "func": "ry", "wires": [8]},
        {"input_idx": [39], "func": "ry", "wires": [9]},
        {"input_idx": [40], "func": "rz", "wires": [0]},
        {"input_idx": [41], "func": "rz", "wires": [1]},
        {"input_idx": [42], "func": "rz", "wires": [2]},
        {"input_idx": [43], "func": "rz", "wires": [3]},
        {"input_idx": [44], "func": "rz", "wires": [4]},
        {"input_idx": [45], "func": "rz", "wires": [5]},
        {"input_idx": [46], "func": "rz", "wires": [6]},
        {"input_idx": [47], "func": "rz", "wires": [7]},
        {"input_idx": [48], "func": "rz", "wires": [8]},
        {"input_idx": [49], "func": "rz", "wires": [9]},
        {"input_idx": [50], "func": "rx", "wires": [0]},
        {"input_idx": [51], "func": "rx", "wires": [1]},
        {"input_idx": [52], "func": "rx", "wires": [2]},
        {"input_idx": [53], "func": "rx", "wires": [3]},
        {"input_idx": [54], "func": "rx", "wires": [4]},
        {"input_idx": [55], "func": "rx", "wires": [5]},
        {"input_idx": [56], "func": "rx", "wires": [6]},
        {"input_idx": [57], "func": "rx", "wires": [7]},
        {"input_idx": [58], "func": "rx", "wires": [8]},
        {"input_idx": [59], "func": "rx", "wires": [9]},
        {"input_idx": [60], "func": "ry", "wires": [0]},
        {"input_idx": [61], "func": "ry", "wires": [1]},
        {"input_idx": [62], "func": "ry", "wires": [2]},
        {"input_idx": [63], "func": "ry", "wires": [3]},
        {"input_idx": [64], "func": "ry", "wires": [4]},
        {"input_idx": [65], "func": "ry", "wires": [5]},
        {"input_idx": [66], "func": "ry", "wires": [6]},
        {"input_idx": [67], "func": "ry", "wires": [7]},
        {"input_idx": [68], "func": "ry", "wires": [8]},
        {"input_idx": [69], "func": "ry", "wires": [9]},
        {"input_idx": [70], "func": "rz", "wires": [0]},
        {"input_idx": [71], "func": "rz", "wires": [1]},
        {"input_idx": [72], "func": "rz", "wires": [2]},
        {"input_idx": [73], "func": "rz", "wires": [3]},
        {"input_idx": [74], "func": "rz", "wires": [4]},
        {"input_idx": [75], "func": "rz", "wires": [5]},
        {"input_idx": [76], "func": "rz", "wires": [6]},
        {"input_idx": [77], "func": "rz", "wires": [7]},
        {"input_idx": [78], "func": "rz", "wires": [8]},
        {"input_idx": [79], "func": "rz", "wires": [9]},
        {"input_idx": [80], "func": "rx", "wires": [0]},
        {"input_idx": [81], "func": "rx", "wires": [1]},
        {"input_idx": [82], "func": "rx", "wires": [2]},
        {"input_idx": [83], "func": "rx", "wires": [3]},
        {"input_idx": [84], "func": "rx", "wires": [4]},
        {"input_idx": [85], "func": "rx", "wires": [5]},
        {"input_idx": [86], "func": "rx", "wires": [6]},
        {"input_idx": [87], "func": "rx", "wires": [7]},
        {"input_idx": [88], "func": "rx", "wires": [8]},
        {"input_idx": [89], "func": "rx", "wires": [9]},
        {"input_idx": [90], "func": "ry", "wires": [0]},
        {"input_idx": [91], "func": "ry", "wires": [1]},
        {"input_idx": [92], "func": "ry", "wires": [2]},
        {"input_idx": [93], "func": "ry", "wires": [3]},
        {"input_idx": [94], "func": "ry", "wires": [4]},
        {"input_idx": [95], "func": "ry", "wires": [5]},
        {"input_idx": [96], "func": "ry", "wires": [6]},
        {"input_idx": [97], "func": "ry", "wires": [7]},
        {"input_idx": [98], "func": "ry", "wires": [8]},
        {"input_idx": [99], "func": "ry", "wires": [9]},
    ],


    "7x7_ryzxyzxy2": [
        {"input_idx": [0], "func":  "ry", "wires": [0 ]},
        {"input_idx": [1], "func":  "ry", "wires": [1 ]},
        {"input_idx": [2], "func":  "ry", "wires": [2 ]},
        {"input_idx": [3], "func":  "ry", "wires": [3 ]},
        {"input_idx": [4], "func":  "ry", "wires": [4 ]},
        {"input_idx": [5], "func":  "ry", "wires": [5 ]},
        {"input_idx": [6], "func":  "ry", "wires": [6 ]},
        {"input_idx": [7], "func":  "ry", "wires": [7 ]},
        {"input_idx": [8], "func":  "ry", "wires": [8 ]},
        {"input_idx": [9], "func":  "ry", "wires": [9 ]},
        {"input_idx": [10], "func": "ry", "wires": [10]},
        {"input_idx": [11], "func": "ry", "wires": [11]},

        {"input_idx": [12], "func": "rz", "wires": [0 ]},
        {"input_idx": [13], "func": "rz", "wires": [1 ]},
        {"input_idx": [14], "func": "rz", "wires": [2 ]},
        {"input_idx": [15], "func": "rz", "wires": [3 ]},
        {"input_idx": [16], "func": "rz", "wires": [4 ]},
        {"input_idx": [17], "func": "rz", "wires": [5 ]},
        {"input_idx": [18], "func": "rz", "wires": [6 ]},
        {"input_idx": [19], "func": "rz", "wires": [7 ]},
        {"input_idx": [20], "func": "rz", "wires": [8 ]},
        {"input_idx": [21], "func": "rz", "wires": [9 ]},
        {"input_idx": [22], "func": "rz", "wires": [10]},
        {"input_idx": [23], "func": "rz", "wires": [11]},

        {"input_idx": [24], "func": "rx", "wires": [0 ]},
        {"input_idx": [25], "func": "rx", "wires": [1 ]},
        {"input_idx": [26], "func": "rx", "wires": [2 ]},
        {"input_idx": [27], "func": "rx", "wires": [3 ]},
        {"input_idx": [28], "func": "rx", "wires": [4 ]},
        {"input_idx": [29], "func": "rx", "wires": [5 ]},
        {"input_idx": [30], "func": "rx", "wires": [6 ]},
        {"input_idx": [31], "func": "rx", "wires": [7 ]},
        {"input_idx": [32], "func": "rx", "wires": [8 ]},
        {"input_idx": [33], "func": "rx", "wires": [9 ]},
        {"input_idx": [34], "func": "rx", "wires": [10]},
        {"input_idx": [35], "func": "rx", "wires": [11]},

        {"input_idx": [36], "func": "rz", "wires": [0 ]},
        {"input_idx": [37], "func": "rz", "wires": [1 ]},
        {"input_idx": [38], "func": "rz", "wires": [2 ]},
        {"input_idx": [39], "func": "rz", "wires": [3 ]},
        {"input_idx": [40], "func": "rz", "wires": [4 ]},
        {"input_idx": [41], "func": "rz", "wires": [5 ]},
        {"input_idx": [42], "func": "rz", "wires": [6 ]},
        {"input_idx": [43], "func": "rz", "wires": [7 ]},
        {"input_idx": [44], "func": "rz", "wires": [8 ]},
        {"input_idx": [45], "func": "rz", "wires": [9 ]},
        {"input_idx": [46], "func": "rz", "wires": [10]},
        {"input_idx": [47], "func": "rz", "wires": [11]},

        {"input_idx": [48], "func": "ry", "wires": [0]},

    ],
   '7x7_ryzxyzxy':
        [
            {'input_idx': [0], 'func': 'ry', 'wires': [0]},
            {'input_idx': [1], 'func': 'ry', 'wires': [1]},
            {'input_idx': [2], 'func': 'ry', 'wires': [2]},
            {'input_idx': [3], 'func': 'ry', 'wires': [3]},
            {'input_idx': [4], 'func': 'ry', 'wires': [4]},
            {'input_idx': [5], 'func': 'ry', 'wires': [5]},
            {'input_idx': [6], 'func': 'ry', 'wires': [6]},
            {'input_idx': [7], 'func': 'ry', 'wires': [7]},
            {'input_idx': [8], 'func': 'ry', 'wires': [8]},
            {'input_idx': [9], 'func': 'ry', 'wires': [9]},
            {'input_idx': [10], 'func': 'rz', 'wires': [0]},
            {'input_idx': [11], 'func': 'rz', 'wires': [1]},
            {'input_idx': [12], 'func': 'rz', 'wires': [2]},
            {'input_idx': [13], 'func': 'rz', 'wires': [3]},
            {'input_idx': [14], 'func': 'rz', 'wires': [4]},
            {'input_idx': [15], 'func': 'rz', 'wires': [5]},
            {'input_idx': [16], 'func': 'rz', 'wires': [6]},
            {'input_idx': [17], 'func': 'rz', 'wires': [7]},
            {'input_idx': [18], 'func': 'rz', 'wires': [8]},
            {'input_idx': [19], 'func': 'rz', 'wires': [9]},
            {'input_idx': [20], 'func': 'rx', 'wires': [0]},
            {'input_idx': [21], 'func': 'rx', 'wires': [1]},
            {'input_idx': [22], 'func': 'rx', 'wires': [2]},
            {'input_idx': [23], 'func': 'rx', 'wires': [3]},
            {'input_idx': [24], 'func': 'rx', 'wires': [4]},
            {'input_idx': [25], 'func': 'rx', 'wires': [5]},
            {'input_idx': [26], 'func': 'rx', 'wires': [6]},
            {'input_idx': [27], 'func': 'rx', 'wires': [7]},
            {'input_idx': [28], 'func': 'rx', 'wires': [8]},
            {'input_idx': [29], 'func': 'rx', 'wires': [9]},
            {'input_idx': [30], 'func': 'ry', 'wires': [0]},
            {'input_idx': [31], 'func': 'ry', 'wires': [1]},
            {'input_idx': [32], 'func': 'ry', 'wires': [2]},
            {'input_idx': [33], 'func': 'ry', 'wires': [3]},
            {'input_idx': [34], 'func': 'ry', 'wires': [4]},
            {'input_idx': [35], 'func': 'ry', 'wires': [5]},
            {'input_idx': [36], 'func': 'ry', 'wires': [6]},
            {'input_idx': [37], 'func': 'ry', 'wires': [7]},
            {'input_idx': [38], 'func': 'ry', 'wires': [8]},
            {'input_idx': [39], 'func': 'ry', 'wires': [9]},
            {'input_idx': [40], 'func': 'rz', 'wires': [0]},
            {'input_idx': [41], 'func': 'rz', 'wires': [1]},
            {'input_idx': [42], 'func': 'rz', 'wires': [2]},
            {'input_idx': [43], 'func': 'rz', 'wires': [3]},
            {'input_idx': [44], 'func': 'rz', 'wires': [4]},
            {'input_idx': [45], 'func': 'rz', 'wires': [5]},
            {'input_idx': [46], 'func': 'rz', 'wires': [6]},
            {'input_idx': [47], 'func': 'rz', 'wires': [7]},
            {'input_idx': [48], 'func': 'rz', 'wires': [8]},
        ],

    "8x8_ryzxyzxy": [
        {"input_idx": [0], "func": "ry", "wires": [0]},
        {"input_idx": [1], "func": "ry", "wires": [1]},
        {"input_idx": [2], "func": "ry", "wires": [2]},
        {"input_idx": [3], "func": "ry", "wires": [3]},
        {"input_idx": [4], "func": "ry", "wires": [4]},
        {"input_idx": [5], "func": "ry", "wires": [5]},
        {"input_idx": [6], "func": "ry", "wires": [6]},
        {"input_idx": [7], "func": "ry", "wires": [7]},
        {"input_idx": [8], "func": "ry", "wires": [8]},
        {"input_idx": [9], "func": "ry", "wires": [9]},
        {"input_idx": [10], "func": "rz", "wires": [0]},
        {"input_idx": [11], "func": "rz", "wires": [1]},
        {"input_idx": [12], "func": "rz", "wires": [2]},
        {"input_idx": [13], "func": "rz", "wires": [3]},
        {"input_idx": [14], "func": "rz", "wires": [4]},
        {"input_idx": [15], "func": "rz", "wires": [5]},
        {"input_idx": [16], "func": "rz", "wires": [6]},
        {"input_idx": [17], "func": "rz", "wires": [7]},
        {"input_idx": [18], "func": "rz", "wires": [8]},
        {"input_idx": [19], "func": "rz", "wires": [9]},
        {"input_idx": [20], "func": "rx", "wires": [0]},
        {"input_idx": [21], "func": "rx", "wires": [1]},
        {"input_idx": [22], "func": "rx", "wires": [2]},
        {"input_idx": [23], "func": "rx", "wires": [3]},
        {"input_idx": [24], "func": "rx", "wires": [4]},
        {"input_idx": [25], "func": "rx", "wires": [5]},
        {"input_idx": [26], "func": "rx", "wires": [6]},
        {"input_idx": [27], "func": "rx", "wires": [7]},
        {"input_idx": [28], "func": "rx", "wires": [8]},
        {"input_idx": [29], "func": "rx", "wires": [9]},
        {"input_idx": [30], "func": "ry", "wires": [0]},
        {"input_idx": [31], "func": "ry", "wires": [1]},
        {"input_idx": [32], "func": "ry", "wires": [2]},
        {"input_idx": [33], "func": "ry", "wires": [3]},
        {"input_idx": [34], "func": "ry", "wires": [4]},
        {"input_idx": [35], "func": "ry", "wires": [5]},
        {"input_idx": [36], "func": "ry", "wires": [6]},
        {"input_idx": [37], "func": "ry", "wires": [7]},
        {"input_idx": [38], "func": "ry", "wires": [8]},
        {"input_idx": [39], "func": "ry", "wires": [9]},
        {"input_idx": [40], "func": "rz", "wires": [0]},
        {"input_idx": [41], "func": "rz", "wires": [1]},
        {"input_idx": [42], "func": "rz", "wires": [2]},
        {"input_idx": [43], "func": "rz", "wires": [3]},
        {"input_idx": [44], "func": "rz", "wires": [4]},
        {"input_idx": [45], "func": "rz", "wires": [5]},
        {"input_idx": [46], "func": "rz", "wires": [6]},
        {"input_idx": [47], "func": "rz", "wires": [7]},
        {"input_idx": [48], "func": "rz", "wires": [8]},
        {"input_idx": [49], "func": "rz", "wires": [9]},
        {"input_idx": [50], "func": "rx", "wires": [0]},
        {"input_idx": [51], "func": "rx", "wires": [1]},
        {"input_idx": [52], "func": "rx", "wires": [2]},
        {"input_idx": [53], "func": "rx", "wires": [3]},
        {"input_idx": [54], "func": "rx", "wires": [4]},
        {"input_idx": [55], "func": "rx", "wires": [5]},
        {"input_idx": [56], "func": "rx", "wires": [6]},
        {"input_idx": [57], "func": "rx", "wires": [7]},
        {"input_idx": [58], "func": "rx", "wires": [8]},
        {"input_idx": [59], "func": "rx", "wires": [9]},
        {"input_idx": [60], "func": "ry", "wires": [0]},
        {"input_idx": [61], "func": "ry", "wires": [1]},
        {"input_idx": [62], "func": "ry", "wires": [2]},
        {"input_idx": [63], "func": "ry", "wires": [3]},
    ],
    "8x2_ryz": [
        {"input_idx": [0], "func": "ry", "wires": [0]},
        {"input_idx": [1], "func": "ry", "wires": [1]},
        {"input_idx": [2], "func": "ry", "wires": [2]},
        {"input_idx": [3], "func": "ry", "wires": [3]},
        {"input_idx": [4], "func": "ry", "wires": [4]},
        {"input_idx": [5], "func": "ry", "wires": [5]},
        {"input_idx": [6], "func": "ry", "wires": [6]},
        {"input_idx": [7], "func": "ry", "wires": [7]},
        {"input_idx": [8], "func": "rz", "wires": [0]},
        {"input_idx": [9], "func": "rz", "wires": [1]},
        {"input_idx": [10], "func": "rz", "wires": [2]},
        {"input_idx": [11], "func": "rz", "wires": [3]},
        {"input_idx": [12], "func": "rz", "wires": [4]},
        {"input_idx": [13], "func": "rz", "wires": [5]},
        {"input_idx": [14], "func": "rz", "wires": [6]},
        {"input_idx": [15], "func": "rz", "wires": [7]},
    ],
    "16x1_ry": [
        {"input_idx": [0], "func": "ry", "wires": [0]},
        {"input_idx": [1], "func": "ry", "wires": [1]},
        {"input_idx": [2], "func": "ry", "wires": [2]},
        {"input_idx": [3], "func": "ry", "wires": [3]},
        {"input_idx": [4], "func": "ry", "wires": [4]},
        {"input_idx": [5], "func": "ry", "wires": [5]},
        {"input_idx": [6], "func": "ry", "wires": [6]},
        {"input_idx": [7], "func": "ry", "wires": [7]},
        {"input_idx": [8], "func": "ry", "wires": [8]},
        {"input_idx": [9], "func": "ry", "wires": [9]},
        {"input_idx": [10], "func": "ry", "wires": [10]},
        {"input_idx": [11], "func": "ry", "wires": [11]},
        {"input_idx": [12], "func": "ry", "wires": [12]},
        {"input_idx": [13], "func": "ry", "wires": [13]},
        {"input_idx": [14], "func": "ry", "wires": [14]},
        {"input_idx": [15], "func": "ry", "wires": [15]},
    ],
}
